package com.example.processmanager.util

object EssentialProcessFilter {
    private val progressFilter = ArrayList<String>()

    init {
        progressFilter.add("android.process.acore");
        progressFilter.add("android.process.media");
        progressFilter.add("android.tts");
        progressFilter.add("android.uid.phone");
        progressFilter.add("android.uid.shared");
        progressFilter.add("android.uid.system");
        progressFilter.add("com.alarmclock.xtreme");
        progressFilter.add("com.amap.android.location");
        progressFilter.add("com.android.ActivityNetwork");
        progressFilter.add("com.android.QuickDial");
        progressFilter.add("com.android.SmsService");
        progressFilter.add("com.android.activate");
        progressFilter.add("com.android.alarmclock");
        progressFilter.add("com.android.bluetooth");
        progressFilter.add("com.android.certinstaller");
        progressFilter.add("com.android.contacts");
        progressFilter.add("com.android.defcontainer");
        progressFilter.add("com.android.deskclock");
        progressFilter.add("com.android.htccontacts");
        progressFilter.add("com.android.htcdialer");
        progressFilter.add("com.android.incallui");
        progressFilter.add("com.android.keychain");
        progressFilter.add("com.android.keyguard");
        progressFilter.add("com.android.lc.calllog");
        progressFilter.add("com.android.mms");
        progressFilter.add("com.android.nfc");
        progressFilter.add("com.android.nfc3");
        progressFilter.add("com.android.phone");
        progressFilter.add("com.android.providers.applications");
        progressFilter.add("com.android.providers.calendar");
        progressFilter.add("com.android.providers.contacts");
        progressFilter.add("com.android.providers.downloads");
        progressFilter.add("com.android.providers.drm");
        progressFilter.add("com.android.providers.htcCheckin");
        progressFilter.add("com.android.providers.media");
        progressFilter.add("com.android.providers.settings");
        progressFilter.add("com.android.providers.subscribedfeeds");
        progressFilter.add("com.android.providers.telephony");
        progressFilter.add("com.android.server.telecom");
        progressFilter.add("com.android.settings");
        progressFilter.add("com.android.smspush");
        progressFilter.add("com.android.stk");
        progressFilter.add("com.android.systemui");
        progressFilter.add("com.android.vending.updater");
        progressFilter.add("com.android.voicedialer");
        progressFilter.add("com.asus.alarmclock");
        progressFilter.add("com.asus.contacts");
        progressFilter.add("com.asus.deskclock");
        progressFilter.add("com.asus.message");
        progressFilter.add("com.baidu.input");
        progressFilter.add("com.bitfire.development.calendarsnooze");
        progressFilter.add("com.cootek.smartinputv5");
        progressFilter.add("com.google.android.apps.gtalkservice");
        progressFilter.add("com.google.android.apps.hangoutsdialer");
        progressFilter.add("com.google.android.apps.uploader");
        progressFilter.add("com.google.android.backup");
        progressFilter.add("com.google.android.contacts");
        progressFilter.add("com.google.android.deskclock");
        progressFilter.add("com.google.android.dialer");
        progressFilter.add("com.google.android.googlequicksearchbox");
        progressFilter.add("com.google.android.gsf");
        progressFilter.add("com.google.android.inputmethod.latin");
        progressFilter.add("com.google.android.inputmethod.latin.dictionarypack");
        progressFilter.add("com.google.android.inputmethod.pinyin");
        progressFilter.add("com.google.android.location");
        progressFilter.add("com.google.android.providers.subsriber");
        progressFilter.add("com.google.android.syncadapters.contacts");
        progressFilter.add("com.google.android.systemupdater");
        progressFilter.add("com.gto.zero.zboost");
        progressFilter.add("com.htc.android.htcime");
        progressFilter.add("com.htc.android.worldclock");
        progressFilter.add("com.htc.bg.uid.shared");
        progressFilter.add("com.htc.contacts");
        progressFilter.add("com.htc.messagecs");
        progressFilter.add("com.htc.opensense");
        progressFilter.add("com.htc.quicklaunchwidget");
        progressFilter.add("com.htc.rosie.uid.shared");
        progressFilter.add("com.htc.widget.clockwidget");
        progressFilter.add("com.huawei.accountagent");
        progressFilter.add("com.huawei.android.gpms");
        progressFilter.add("com.huawei.systemmanager");
        progressFilter.add("com.huawei.widget.localcityweatherclock");
        progressFilter.add("com.iflytek.inputmethod");
        progressFilter.add("com.jb.emoji.gokeyboard");
        progressFilter.add("com.jb.goime");
        progressFilter.add("com.jb.gokeyboard");
        progressFilter.add("com.jb.lab.gokeyboard");
        progressFilter.add("com.jbapps.contactpro");
        progressFilter.add("com.kingroot.kinguser");
        progressFilter.add("com.koushikdutta.klaxon");
        progressFilter.add("com.kunpeng.hipb");
        progressFilter.add("com.lge.android.atservice");
        progressFilter.add("com.lge.ia");
        progressFilter.add("com.lge.ia.task.mrgdblogger");
        progressFilter.add("com.lge.ime");
        progressFilter.add("com.lge.ims");
        progressFilter.add("com.lge.keepscreenon");
        progressFilter.add("com.lge.ltecall");
        progressFilter.add("com.lge.mrg.service");
        progressFilter.add("com.lge.simcontacts");
        progressFilter.add("com.lge.splitwindow");
        progressFilter.add("com.lge.systemservice");
        progressFilter.add("com.mediatek.atci.service");
        progressFilter.add("com.mediatek.bluetooth");
        progressFilter.add("com.mediatek.thermalmanager");
        progressFilter.add("com.meizu.mzsyncservice");
        progressFilter.add("com.motorola.android.phoneportal.androidui");
        progressFilter.add("com.motorola.audiomonitor");
        progressFilter.add("com.motorola.bach.modemstats");
        progressFilter.add("com.motorola.blur.alarmclock");
        progressFilter.add("com.motorola.blur.contacts");
        progressFilter.add("com.motorola.blur.contacts.data");
        progressFilter.add("com.motorola.blur.conversations");
        progressFilter.add("com.motorola.blur.friendfeed");
        progressFilter.add("com.motorola.blur.home.clock");
        progressFilter.add("com.motorola.blur.home.synccontrol");
        progressFilter.add("com.motorola.blur.news");
        progressFilter.add("com.motorola.contacts");
        progressFilter.add("com.motorola.hiddenmenu");
        progressFilter.add("com.motorola.mmsp.motohome");
        progressFilter.add("com.motorola.motgeofencesvc");
        progressFilter.add("com.motorola.motocare");
        progressFilter.add("com.motorola.numberlocation");
        progressFilter.add("com.motorola.process.system");
        progressFilter.add("com.motorola.slpc_sys");
        progressFilter.add("com.motorola.thumbnailservice");
        progressFilter.add("com.motorola.usb");
        progressFilter.add("com.motorola.widgetapp.worldclock");
        progressFilter.add("com.motorola.wirelessdisplay.service");
        progressFilter.add("com.nuance.swype.emui");
        progressFilter.add("com.ontim.clock");
        progressFilter.add("com.qualcomm.location");
        progressFilter.add("com.qualcomm.services.location");
        progressFilter.add("com.qualcomm.wfd.service");
        progressFilter.add("com.redbend.vdmc");
        progressFilter.add("com.samsung.android.providers.context");
        progressFilter.add("com.samsung.inputmethod");
        progressFilter.add("com.samsung.sec.android.application.csc");
        progressFilter.add("com.sec.android.app.FileTransferManager");
        progressFilter.add("com.sec.android.app.clockpackage");
        progressFilter.add("com.sec.android.app.controlpanel");
        progressFilter.add("com.sec.android.app.keyguard");
        progressFilter.add("com.sec.android.app.launcher");
        progressFilter.add("com.sec.android.provider.logsprovider");
        progressFilter.add("com.sec.android.providers.security");
        progressFilter.add("com.sec.android.widgetapp.favoriteswidget");
        progressFilter.add("com.sec.android.widgetapp.stockclock");
        progressFilter.add("com.sec.android.widgetapp.weatherclock");
        progressFilter.add("com.sec.msc.nts.android.proxy");
        progressFilter.add("com.sohu.inputmethod.sogou");
        progressFilter.add("com.sonyericsson.alarm");
        progressFilter.add("com.sonyericsson.customization");
        progressFilter.add("com.sonyericsson.devicemonitor");
        progressFilter.add("com.sonyericsson.digitalclockwidget");
        progressFilter.add("com.sonyericsson.eventstream.calllogplugin");
        progressFilter.add("com.sonyericsson.organizer");
        progressFilter.add("com.sonyericsson.provider.useragent");
        progressFilter.add("com.sonyericsson.psm.sysmonservice");
        progressFilter.add("com.sonyericsson.secureclockservice");
        progressFilter.add("com.sonyericsson.smartcard");
        progressFilter.add("com.sonyericsson.usbux");
        progressFilter.add("com.sonyericsson.widget.digitalclock");
        progressFilter.add("com.splunchy.android.alarmclock");
        progressFilter.add("com.tencent.qqpinyin");
        progressFilter.add("com.towalds.android");
        progressFilter.add("com.youlu");
        progressFilter.add("com.yulong.android.coolpadime");
        progressFilter.add("com.zdworks.android.zdclock");
        progressFilter.add("com.zxly.assist");
        progressFilter.add("org.simalliance.openmobileapi.service");
        progressFilter.add("org.woodroid.alarmbird");
        progressFilter.add("org.woodroid.alarmlady");
        progressFilter.add("system");
        progressFilter.add("zte.com.cn.alarmclock");
        progressFilter.add("com.sonymobile.swiqisettingsservice");
        progressFilter.add("com.sonyericsson.usbotg");
        progressFilter.add("com.sonyericsson.audioeffectservice");
        progressFilter.add("com.sonymobile.superstamina");
        progressFilter.add("com.sonyericsson.tvout.mhl");
        progressFilter.add("com.google.android.gms");
    }

    fun isProgressFilter(pkgName: String, isSys: Boolean): Boolean {
        if (isProgressFilter(pkgName)) {
            return true
        }
        return isSys && (pkgName.contains("dialer") || pkgName.contains("phone") || pkgName.contains("contacts") || pkgName.equals("android", ignoreCase = true) || pkgName.equals("top", ignoreCase = true))
    }

    fun isProgressFilter(pkgName: String): Boolean {
        return progressFilter.contains(pkgName)
    }
}